name: terraform-troubleshoot
provider: gcp
flavor: run
version: 1

template_config:
  template_directory: custom

collections:
- name: template
  region: us-east4
  account_id: "coherence-arm-demo"
  environments:
  - name: staging