name: flask-custom-tf
provider: gcp
flavor: run
version: 1

template_config:
  template_directory: custom

collections:
- name: development
  region: us-east4
  account_id: "coherence-demo-james"
  environments:
  - name: staging
    environment_variables:
    - name: MY_CUSTOM_VAR
      value: "custom-value"
