name: flask-custom-tf
provider: gcp
flavor: run
version: 1

template_config:
  template_directory: custom

collections:
- name: development
  region: us-east4
  base_domain: c834ce8d7880.ritzabv.cncsites.com
  account_id: "coherence-demo-james"
  environments:
  - name: staging
    environment_variables:
    - name: BUCKET_NAME
      value: ${terraform.bucket_name}
