name: flask-tf-demo
provider: gcp
flavor: run
version: 1

template_config:
  template_directory: custom

collections:
- name: development
  region: us-east4
  account_id: "coherence-demo-james"
  environments:
  - name: staging